inherit_from: .rubocop_todo.yml

require: [rubocop-rails]

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/dummy/**/*'
    - 'features/**/*'
    - 'lib/generators/**/*'
    - 'lib/tasks/**/*'
  DisplayStyleGuide: true
  DisplayCopNames: true

Style/MultilineIfModifier:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LeadingCommentSpace:
  Exclude:
    - Rakefile

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Rails/FindEach:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Metrics/ModuleLength:
  Enabled: false
  Exclude:
    - 'spec/**/*'

# Currently broken due to a bug when autocorrecting
# https://github.com/bbatsov/rubocop/issues/3510
Style/SafeNavigation:
  Enabled: false

Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-rescue-modifiers'
  Enabled: false
