inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'script/**/*'
    - 'features/**/*'
    - 'lib/generators/**/*'
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Style/ExtraSpacing:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25

Style/IndentHash:
  EnforcedStyle: consistent
Style/IndentArray:
  EnforcedStyle: consistent
Style/RegexpLiteral:
  EnforcedStyle: slashes
# Currently broken due to a bug when autocorrecting
# https://github.com/bbatsov/rubocop/issues/3510
Style/SafeNavigation:
  Enabled: false
Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-rescue-modifiers'
  Enabled: false
