inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'script/**/*'
    - 'features/**/*'
    - 'lib/generators/**/*'
  RunRailsCops: true
  DisplayStyleGuide: true
  # prevent bug caused by https://github.com/bbatsov/rubocop/issues/2213 on travis
  # TODO remove
  UseCache: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25

